[versions]
asm = "9.10.1"
okio = "3.18.1"
kotlin = "2.4.10"

commons = "1.0.5-SNAPSHOT"

jb_annotations = "26.1.0"

kmp_zip = "0.15.0"

kotlin_serialization = "1.11.0"
kotlin_coroutines = "1.11.0"
kotlin_logging = "8.0.4"
kotlin_atomicfu = "0.33.0"

clikt = "5.1.0"
slf4j = "2.0.18"

resources = "0.16.0"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm_commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm_util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
asm_analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }
asm_tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

commons_kt = { module = "xyz.wagyourtail.commons:commons-kt", version.ref = "commons" }

jetbrains_annotations_kmp = { module = "org.jetbrains:annotations", version.ref = "jb_annotations" }
kmp_zip = { module = "no.synth:kmp-zip", version.ref = "kmp_zip" }
kmp_zip_okio = { module = "no.synth:kmp-zip-okio", version.ref = "kmp_zip" }

kotlin_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin_coroutines" }
kotlin_coroutines_tests = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin_coroutines" }
kotlin_serialization_json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin_serialization" }
kotlin_logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin_logging" }

clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }

slf4j_api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j_simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

resources = { module = "com.goncalossilva:resources", version.ref = "resources" }

[bundles]
asm = [
    "asm",
#    "asm_commons",
#    "asm_util",
#    "asm_analysis",
    "asm_tree"
]

[plugins]
commons = { id = "xyz.wagyourtail.commons-gradle", version.ref = "commons" }
kotlinx_atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "kotlin_atomicfu" }
resources = { id = "com.goncalossilva.resources", version.ref = "resources" }
