package xyz.wagyourtail.unimined.mapping.tree

interface SignaturePropertyView: NamespacedPropertyView<SignaturePropertyView>
interface SignatureProperty: SignaturePropertyView, NamespacedProperty<SignaturePropertyView>